//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADPUK.NINA.AddToAlignmentModel.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADPUK.NINA.AddToAlignmentModel.Locales.ViewStrings", typeof(ViewStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow use with mounts other than Alt-Az. - EXPERIMENTAL USE WITH CARE.
        /// </summary>
        public static string AllowNonAltAzMounts {
            get {
                return ResourceManager.GetString("AllowNonAltAzMounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only works with AltAz mounts.
        /// </summary>
        public static string AltAzOnly {
            get {
                return ResourceManager.GetString("AltAzOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure the scope is roughly pointing at the horizon due north..
        /// </summary>
        public static string EnsureNorth {
            get {
                return ResourceManager.GetString("EnsureNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure the scope is roughly pointing at the horizon due south.
        /// </summary>
        public static string EnsureSouth {
            get {
                return ResourceManager.GetString("EnsureSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this correct?.
        /// </summary>
        public static string IsThisCorrect {
            get {
                return ResourceManager.GetString("IsThisCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Elevation.
        /// </summary>
        public static string MaximumElevation {
            get {
                return ResourceManager.GetString("MaximumElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Elevation Above Horizon.
        /// </summary>
        public static string MinElevationAboveHorizon {
            get {
                return ResourceManager.GetString("MinElevationAboveHorizon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Elevation.
        /// </summary>
        public static string MinimumElevation {
            get {
                return ResourceManager.GetString("MinimumElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope pre-alignment to northern horizon not confirmed.
        /// </summary>
        public static string NorthNotConfirmed {
            get {
                return ResourceManager.GetString("NorthNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Altitude Points.
        /// </summary>
        public static string NumberOfAltitudePoints {
            get {
                return ResourceManager.GetString("NumberOfAltitudePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Azimuth Points.
        /// </summary>
        public static string NumberOfAzimuthPoints {
            get {
                return ResourceManager.GetString("NumberOfAzimuthPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Alignment.
        /// </summary>
        public static string PreAlignment {
            get {
                return ResourceManager.GetString("PreAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount must be connected via CPWI.
        /// </summary>
        public static string RequireCPWI {
            get {
                return ResourceManager.GetString("RequireCPWI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope is pointing to Az: {{Azimuth}}, Alt: {{Altitude}}.
        /// </summary>
        public static string ScopeAltAzCoordinates {
            get {
                return ResourceManager.GetString("ScopeAltAzCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope not point to pole and/or horizon.
        /// </summary>
        public static string ScopeNotAtZero {
            get {
                return ResourceManager.GetString("ScopeNotAtZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve Attempts.
        /// </summary>
        public static string SolveAttempts {
            get {
                return ResourceManager.GetString("SolveAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope pre-alignment to southern horizon not confirmed.
        /// </summary>
        public static string SouthNotConfirmed {
            get {
                return ResourceManager.GetString("SouthNotConfirmed", resourceCulture);
            }
        }
    }
}
